name: Deploy ACA Image
run-name: Deploy ACA Image (dev)

on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

env:
  IMAGE_TO_DEPLOY: "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
  CONTAINER_APP_NAME: "ca-myapp-3-dev-weu"
  RESOURCE_GROUP: "rg-platform-noncritical-dev-weu"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ACA Image
    environment: dev
    steps:
      - name: Azure login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy hello-world image
        run: |
          az extension add --name containerapp --upgrade
          az containerapp update \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$IMAGE_TO_DEPLOY" \
            --output none
